In [ ]:
import unicodedata

votacao = {"CORINTHIANS": 0, "PALMEIRAS" : 0, "SAO PAULO" : 0, "SANTOS": 0}
lista = []

while(True):
  cpf = input("""Digite seu cpf para iniciar votação ou aperte enter para finalizar: """)
  if (cpf == ''):
      break
  while (True):
    if (len(cpf) != 11):
      cpf = input("cpf invalido, digite seu cpf novamente: ")
    else:
      time = input("""
       ______________________________________________________
      |                  Sistema de votação                  |
       ======================================================
      | escolha entre um dos times abaixo digitando seu nome |
       =====================================================
      |     Corinthians | Palmeiras | São Paulo | Santos     |
       =======================================================
      | DE UMA RESPOSTA EM BRANCO PARA VOTAR NULO            |
      > ...""")

      # Lidando com multiplas formas de escrever o nome dos times
      time = time.upper() # Transforma todas as letras para maiusculo
      time = unicodedata.normalize("NFD", time) # Retira acentos
      time = time.encode("ascii", "ignore")
      time = time.decode("utf-8")

      cpf_validacao = input("Digite seu cpf novamente para validação: ")

      if ((cpf_validacao == cpf) and ((time == "CORINTHIANS") or (time == "SAO PAULO") or (time == "PALMEIRAS")  or (time == "SANTOS")  or (time == ""))):
        lista.append(time)
        if (time != ''):
          votacao[time] += 1
        print("| Votação computada |")
        break
      else:
        print("CPF ou entrada de time inválido, voto não computado")
        break

mais_votos = votacao.get('CORINTHIANS')
for time, votos in votacao.items():
  print(f"{time}: {votos}")
  if (votacao.get(time, votos) > mais_votos):
    mais_votos = votacao.get(time, votos)

for time, votos in votacao.items():
    if (votos == mais_votos):
      print(f"O(s) mais votado(s) foi(ram) {time} com {votos} votos")







Digite seu cpf para iniciar votação ou aperte enter para finalizar: 11111111111

       ______________________________________________________
      |                  Sistema de votação                  |
      | escolha entre um dos times abaixo digitando seu nome |
      |     Corinthians | Palmeiras | São Paulo | Santos     |
      | DE UMA RESPOSTA EM BRANCO PARA VOTAR NULO            |  
      > ...Corinthians
Digite seu cpf novamente para validação: 11111111111
| Votação computada |
Digite seu cpf para iniciar votação ou aperte enter para finalizar: 11111111111

       ______________________________________________________
      |                  Sistema de votação                  |
      | escolha entre um dos times abaixo digitando seu nome |
      |     Corinthians | Palmeiras | São Paulo | Santos     |
      | DE UMA RESPOSTA EM BRANCO PARA VOTAR NULO            |  
      > ...Palmeiras
Digite seu cpf novamente para validação: 1111111111
CPF ou entrada de time inválido, vo

In [ ]:
import numpy as np


ordem = int(input("Digite a ordem da matriz: "))
matriz = []
print("Digite os elementos da matriz, um por vez")
for i in range(ordem):
    linha = []
    for j in range(ordem):
        linha.append(float(input()))
    matriz.append(linha)

matriz_np = np.array(matriz, dtype=float)



# Verifica se a matriz é inversível
if np.isclose(np.linalg.det(matriz_np), 0.0):
    print("A matriz não é inversível.")
else:
    # Método 1: Inversa usando NumPy
    print("Matriz")
    print(matriz_np)
    inversa_np = np.linalg.inv(matriz_np)
    print("\nInversa (NumPy):")
    print(inversa_np)

    # Método 2: Inversa manual (usando cofatores e determinante)
    matriz_cofatores = np.zeros((ordem, ordem))
    for i in range(ordem):
        for j in range(ordem):
            menor = np.delete(np.delete(matriz_np, i, axis=0), j, axis=1)
            matriz_cofatores[i][j] = ((-1) ** (i + j)) * np.linalg.det(menor)

    matriz_adjunta = matriz_cofatores.T
    inversa_semnp = matriz_adjunta / np.linalg.det(matriz_np)
    print("\nInversa (Sem numpy.linalg.inv()):")
    print(inversa_semnp)

Digite a ordem da matriz: 2
Digite os elementos da matriz, um por vez
1
2
3
4
Matriz
[[1. 2.]
 [3. 4.]]

Inversa (NumPy):
[[-2.   1. ]
 [ 1.5 -0.5]]

Inversa (Manual):
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np

print("Informe as ordens das duas matrizes (linhas colunas):")
linhas_A, colunas_A = map(int, input("Matriz A: ").split())
linhas_B, colunas_B = map(int, input("Matriz B: ").split())

print(f"\nMatriz A {linhas_A}x{colunas_A}:")
A = np.random.randint(0, 10, size=(linhas_A, colunas_A))
print(A)

print(f"\nMatriz B {linhas_B}x{colunas_B}:")
B = np.random.randint(0, 10, size=(linhas_B, colunas_B))
print(B)

# Verificar se a multiplicação é possível
if colunas_A != linhas_B:
    print("\nNão é possível multiplicar as matrizes!")
else:
    resultado = np.zeros((linhas_A, colunas_B), dtype=int)

    for i in range(linhas_A):
        for j in range(colunas_B):
            soma = 0
            for k in range(colunas_A):
                soma += A[i, k] * B[k, j]
            resultado[i, j] = soma

    print("\nResultado da multiplicação A × B:")
    print(resultado)

Informe as ordens das duas matrizes (linhas colunas):
Matriz A: 2 3
Matriz B: 3 2

Matriz A 2x3:
[[5 9 5]
 [9 9 1]]

Matriz B 3x2:
[[5 9]
 [7 3]
 [6 4]]

Resultado da multiplicação A × B:
[[118  92]
 [114 112]]
